FROM node:20-slim

RUN apt-get update && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./
COPY tsconfig*.json ./
COPY nest-cli.json ./

RUN npm install

COPY prisma ./prisma/
RUN npm run prisma:generate

EXPOSE 3000

CMD ["npm", "run", "start:dev"]
